### ISSUE TITLE
It is in the games section of Discover (flatpak front-end)

### ISSUE THREAD

**Issue by Ytrog** [inercia/k3x#31]
It is currently in the Games section of Discover.
![K3X](https://user-images.githubusercontent.com/2880376/159369598-ece73f9b-3329-4a0d-a1cd-45e7c7e307b9.png)

**Comment by ThubLives** [comment]
It's listed under "Games" on the flathub.org site as well.  Presumably this is in the Flatpak metadata, rather than a clerical error when submitting it to flathub.org.

**Comment by inercia** [comment]
Fixed on #28
